<?php

return [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'rules' => [
        // frontend
        '' => 'frontend/home/index',
        'index.php' => 'frontend/home/index',
        'homepage.html' => 'frontend/home/index',
        'account/frontend/home'=>'frontend/home/index',
        'account'=>'frontend/home/index',
        'account/frontend/home/index'=>'frontend/home/index',
        'GET category-<categoryId:[0-9]+>.html' => 'frontend/home/index',
        'GET contact.html' => 'frontend/contact/index',
        'GET news-<id:[0-9]+>-<categoryId:[0-9]+>.html' => 'frontend/news/index',
    	'GET 404.html' => 'frontend/error/index',
        'backend' => 'backend/shop/index',
        'GET account/shipping/notify.html' => 'account/shipping/notify',
        'GET account/shipping/mypackage.html' => 'account/shipping/mypackage',
        'GET account/profile.html' => 'account/profile/index',
        'POST account/profile.html' => 'account/profile/index',
        'GET account/info.html' => 'account/profile/info',
        'GET account/order/proforma-invoice-<bincode:[0-9A-Za-z_-]+>.html' => 'account/order/invoice',
        'GET account/order/<status:[0-9A-Za-z_-]+>.html' => 'account/order/index',
        'GET account/order.html' => 'account/order/index',
        'account/service/<controller:\w+>/<action:\w+>.json' => 'account/service/<controller>/<action>',
       
        'account/wallet/rechargetoken.html'=>'account/wallet/rechargetoken',
        'account/wallet/rechargeprimary.html'=>'account/wallet/rechargeprimary',
        'account/wallet/withdrawal.html' => 'account/wallet/withdrawalbit',
        'account/wallet/withdrawalinterest.html' => 'account/wallet/withdrawalinterest',
        'account/wallet/withdrawalrose.html' => 'account/wallet/withdrawalrose',
        'account/wallet/withdrawalpromotion.html' => 'account/wallet/withdrawalpromotion',
        
        'account/wallet/list-primary.html' => 'account/wallet/primary',
        'account/wallet/list-token.html' => 'account/wallet/index',
        'account/wallet/interest.html' => 'account/wallet/interest',
        'account/wallet/rose.html' => 'account/wallet/rose',
        'account/wallet/promotion.html' => 'account/wallet/promotion',
        'account/wallet/presenter.html' => 'account/wallet/presenter',
        
        'account/wallet/active.html' => 'account/wallet/activewallet',
        'account/wallet/verifywallet.html' => 'account/wallet/startwallet',
        'account/wallet/detail-<transactionCode:[0-9A-Za-z_-]+>.html' => 'account/wallet/detail',
        'account/wallet/detailinterest-<transactionCode:[0-9A-Za-z_-]+>.html' => 'account/wallet/detailinterest',
        'account/wallet/paymentwallet.html' => 'account/wallet/checkpaymentwallet',
        'account/wallet/paymenttopup.html' => 'account/wallet/checkpayment',
        'account/wallet/sucessed.html' => 'frontend/account/wallet/sucessed',
        'account/wallet/changeemail.html' => 'frontend/account/wallet/changeemail',
        'account/wallet/changephone.html' => 'frontend/account/wallet/changephone',
        'account/authentication.html'=>'account/wallet/authentication',
        'account/wallet/verify.html' => 'account/wallet/verifywallet',
     
        'GET captcha.html' => 'frontend/user/captcha',
        'GET captcha2.html' => 'account/profile/captcha',
        'GET logout.html' => 'frontend/user/logout',
        'POST logout.html' => 'frontend/user/logout',
        'GET login.html' => 'frontend/user/login',
        'POST login.html' => 'frontend/user/login',
        'GET register.html' => 'frontend/user/register',
        'POST register.html' => 'frontend/user/register',
        'new-password.html' => 'frontend/user/reset',
        'forgot-password.html' => 'frontend/user/forgot',
        'formverify.html' => 'frontend/user/formverify',
        'GET verify/<id:[0-9]+>-<token:[0-9A-Za-z_-]+>.html' => 'frontend/user/verify',
        //'GET reset-password/<id:[0-9]+>-<token:[0-9A-Za-z_-]+>.html' => 'frontend/user/reset',
        'frontend/service/<controller:\w+>/<action:\w+>.json' => 'frontend/service/<controller>/<action>',
        'active-messenger.html'=>'frontend/messenger/active',
    ]
];
